language: node_js
node_js:
    - 10
services:
    - postgresql

cache: npm

before_script:
    - psql -c 'create database testdb;' -U postgres

install:
    - export DATABASE_URL=postgres://postgres:@localhost:5432/testdb
    - export PORT=6400
    - yarn
    - yarn migrate
    - yarn test
    - cp logs/jest/lcov.info ./
