language: node_js
node_js:
    - 10
services:
    - postgresql

cache: npm

install:
    - psql -c 'create database testdb;' -U postgres
    - export DATABASE_URL=postgres://postgres:@localhost:5432/testdb
    - export PORT=6400
    - yarn
    - yarn migrate
    - yarn test --detectOpenHandles
    - cat logs/jest/lcov.info | coveralls
