# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:10.15

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/myongo:3.4.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "yarn.lock" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: yarn

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "yarn.lock" }}

            - run: yarn build

            - run: yarn test-all

            - run: sudo apt-get install -y python3-pip

            - run: sudo pip3 install awscli

            - run: aws s3 sync build s3://lencse-circleci-artifacts/$CIRCLE_PROJECT_REPONAME/$CIRCLE_SHA1/build --region us-east-1 --delete

            - run: aws s3 sync public s3://lencse-circleci-artifacts/$CIRCLE_PROJECT_REPONAME/$CIRCLE_SHA1/public --region us-east-1 --delete

    deploy-to-staging:
        docker:
            - image: buildpack-deps:trusty

        working_directory: ~/repo

        steps:
            - checkout

            - run: sudo apt-get install -y python3-pip

            - run: sudo pip3 install awscli

            - run: aws s3 sync s3://lencse-circleci-artifacts/$CIRCLE_PROJECT_REPONAME/$CIRCLE_SHA1/build build --region us-east-1 --delete

            - run: aws s3 sync s3://lencse-circleci-artifacts/$CIRCLE_PROJECT_REPONAME/$CIRCLE_SHA1/public public --region us-east-1 --delete

            - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git master

workflows:
    version: 2
    standard:
        jobs:
            - build
            - deploy-to-staging:
                requires:
                    - build
            # - approve:
            #     type: approval
            #     requires:
            #         - deploy-to-staging
            # - deploy-to-prod:
            #     requires:
            #         - approve
            # - benchmark:
            #     requires:
            #         - build
