# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.15
              environment:
                PORT: 5600
                DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

            - image: circleci/postgres:11-alpine
              environment:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: postgres

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "yarn.lock" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: yarn

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "yarn.lock" }}

            - run: yarn build

            - run: yarn migrate

            - run: yarn test-all

    code-analyze:
        docker:
            - image: circleci/node:10.15
              environment:
                PORT: 5600
                DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

            - image: circleci/postgres:11-alpine
              environment:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: postgres
        working_directory: ~/repo
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "yarn.lock" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run:
                name: Set up Sonarcloud client
                command: .circleci/setup-sonarcloud.sh
            - run:
                name: Add sonar dir to PATH
                command:
                    source $BASH_ENV
            - run:
                name: Check Sonarcloud setup
                command:
                    sonar-scanner --version

            - run: yarn

            - run: yarn migrate

            - run:
                 name: Test coverage
                 command: yarn test
            - run:
                name: Run sonar console
                command: |
                    sonar-scanner \
                        -Dsonar.projectKey=$SONARCLOUD_PROJECT \
                        -Dsonar.organization=$SONARCLOUD_ORGANIZATION \
                        -Dsonar.sources=src \
                        -Dsonar.host.url=$SONARCLOUD_URL \
                        -Dsonar.login=$SONARCLOUD_LOGIN \
                        -Dsonar.exclusions=logs/**,node_modules/**,build/** \
                        -Dsonar.testExecutionReportPaths=logs/jest/test-reporter.xml \
                        -Dsonar.typescript.lcov.reportPaths=logs/jest/lcov.info

    deploy-to-staging:
        docker:
            - image: buildpack-deps:trusty

        working_directory: ~/repo

        steps:
            - checkout

            - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git master

workflows:
    version: 2
    standard:
        jobs:
            - build
            - deploy-to-staging:
                requires:
                    - build
            - code-analyze:
                requires:
                    - build
            # - approve:
            #     type: approval
            #     requires:
            #         - deploy-to-staging
            # - deploy-to-prod:
            #     requires:
            #         - approve
            # - benchmark:
            #     requires:
            #         - build
